language: c

os:
  - linux
  - osx

dist: focal

cache: ccache

git:
  quiet: true
  depth: 3

before_install:
  - uname -a
  - date

install:

before_script:

script:
  - touch .devel
  - echo configure
  - ./configure
  - echo ls -l
  - ls -l scanner.h grammar.h grammar.c scanner.c || true
  - echo make clean
  - make clean
  - echo ls -l
  - ls -l scanner.h grammar.h grammar.c scanner.c || true
  - echo make
  - make
  - echo ls -l
  - ls -l scanner.h grammar.h grammar.c scanner.c || true
  - if [ "$TRAVIS_OS_NAME" = osx ]; then sleep 10; fi
