language: c

os:
  - linux
  - osx

dist: focal

cache: ccache

git:
  quiet: true
  depth: 3

before_install:
  - uname -a
  - date

install:

before_script:

script:
  - ./build_matrix.sh
  - if [ "$TRAVIS_OS_NAME" = osx ]; then sleep 10; fi
